### ISSUE TITLE
Package for older hardware

### ISSUE THREAD

**Issue by anishsheela** [smc/Indic-Keyboard#11]
The package is not compatible with ARMv6 processor phones. This particularly applies to phones that are flashed with newer versions of android.

Test Case
Phone: LG E510 (LG Optimus Hub)
Details: http://www.gsmarena.com/lg_optimus_hub-4157.php
Android Version: 4.1.2
Kernel Version: 2.6.35.10-perf+cm10
CPU: ARMv6 Compatible processor rev5 (v6l)
Cyanogenmod Version: 10-20121218-UNOFFICIAL-e510

**Comment by jishnu7** [comment]
This is a really old issue. Closing it now. feel free to re-open if you are still facing the issue.
