### ISSUE TITLE
ക്രോം ബ്രൗസറിൽ ലിപ്യന്തരണം കീബോർഡ് വഴി മലയാളം നേരെ ടൈപ്പ് ചെയ്യാൻ കഴിയുന്നില്ല.

### ISSUE THREAD

**Issue by anoopnarayanan** [smc/Indic-Keyboard#28]
ഈയിടെയായി ഇൻഡിക് കീബോർഡിൽ ഒരു പ്രശ്നം കാണുന്നു. മൊബൈലിലെ ക്രോം ബ്രൗസറിൽ ഫേസ്‌ബുക്ക് ഉപയോഗിക്കുമ്പോൾ ( ഫേസ്‌ബുക്ക് ചാറ്റ് മെയിൻ ആപ്പിൽ നിന്നു വേർപെടുത്തിയതിൽ പിന്നെ ഫേസ്‌ബുക്ക് ആപ്പ് ഉപയോഗിക്കാറില്ല. ബ്രൗസറിലേ എടുക്കാറുള്ളൂ) അതിലെ പോസ്റ്റ് കമന്റ് എന്നിവിടങ്ങളിൽ ലിപ്യന്തരണം വഴി മലയാളത്തിലെഴുതുമ്പോൾ ആദ്യ അക്ഷരം കഴിഞ്ഞാൽ പിന്നീടുള്ള അക്ഷരങ്ങൾ ഇംഗ്ലീഷിലായി പോകുന്നു (സ്ക്രീൻ ഷോട്ട് കാണുക) അവ മലയാളത്തിലാക്കണമെങ്കിൽ പിന്നെ ഒരക്ഷരം നീക്കി വീണ്ടും ടൈപ്പ് ചെയ്തു തുടങ്ങണം. ഫേസ്ബുക്കിലെ ടെക്സ്റ്റ് ഏരിയയിൽ മാത്രമേ ഈ പ്രശ്നം കാണുന്നുള്ളൂ. മറ്റിടങ്ങളിൽ നേരെ പ്രവർത്തിക്കുന്നുണ്ട്.

കൂടുതൽ വിവരങ്ങൾ https://www.facebook.com/photo.php?fbid=10152736088205733&set=a.10150264021940733.378666.701470732&type=1&theater&notif_t=like കാണുക

**Comment by jishnu7** [comment]
rewrote transliteration code. So this must be fixed now.

you can re-open if needed.
