### ISSUE TITLE
Give user a choice for entering atomic chillu

### ISSUE THREAD

**Issue by asdofindia** [smc/Indic-Keyboard#29]
Can indic prime be extended to support entry of atomic chillus?

Maybe something like:
- A setting in keyboard preference like "convert to atomic chillus" 
- That setting is checked 
- Indic keyboard automatically converts the conventionally entered chillu as atomic chillu

That way you won't even have to give it a space in the layout.

Or maybe any other better way 
##

**Comment by jishnu7** [comment]
issue moved to github: https://gitlab.com/smc/indic-keyboard/issues/42
