### ISSUE TITLE
ഇൻസ്ക്രിപ്റ്റ് മലയാളം

### ISSUE THREAD

**Issue by rahul-v** [smc/Indic-Keyboard#3]
ഇൻസ്ക്രിപ്റ്റ് മലയാളം കീബോർഡിൽ ഷിഫ്റ്റ് കീകളെകൂടെ ഗ്രേഷേഡോടുകൂടിയോ മറ്റോ ഡിസ്പ്ലെ ചെയ്യിച്ചാൽ നന്നായിരുന്നു. ഉദാ 
![screenshot_2014-03-12-14-15-57](https://f.cloud.github.com/assets/2526929/2395160/b5a2069e-a9c4-11e3-9000-e25999d6f840.png)
 ഇത് പോലെ. അങ്ങനെയെങ്കിൽ ഇൻസ്ക്രിപ്റ്റ് പടിച്ചു തുടങ്ങുന്നവർക്കും പെട്ടന്ന് മൊബിലിലെ ചെറിയ സ്ക്രീനിൽ കീബോഡ് കാണുമ്പോളും ഉള്ള ആശയക്കുഴപ്പം മാറായേനെ. പിന്നെ ഒരു അക്ഷരത്തിൽ ഡീപ്പ് പ്രസ്സ് ചെയ്താൽ അതിന്റെ ഷിഫ്റ്റ് അവസ്ഥയിലുള്ള കീ കിട്ടുന്ന സംവിധാനം ഓപ്ഷണലായി ഉൾപ്പെടുത്തുന്നതും ഉചിതമായിരിക്കുമെന്ന് തോന്നുന്നു. എപ്പോളും ഷിഫ്റ്റിന്റെ അടുത്തേക്ക് വിരള് കൊണ്ട് പോകാത്തവർക്കും നല്ലതല്ലെ. ൺൻ
2. ZWNJ എന്ന കീയും  കൂടി കീബോഡില് ഉൾപ്പെടുത്തേണ്ടതല്ലെ
3. പിന്നെ ആണവ ചില്ല് ടൈപ്പ് ചെയ്യാൻ പറ്റുന്നില്ല എന്നതാണ്. മൊബൈലില് ചില്ലക്ഷരങ്ങൾക്ക് മൂന്ന് കീ അമർത്തേണ്ട ബുദ്ധിമുട്ടും കണക്കിലെടുത്ത് ആണവ ചില്ല് സപ്പോർട്ട് കൂടി ചേർക്കണമെന്നാണ് അഭ്യർത്ഥന
##

**Comment by jishnu7** [comment]
Moved issue to gitlab https://gitlab.com/smc/indic-keyboard/issues/32
