### ISSUE TITLE
Running in android Studio

### ISSUE THREAD

**Issue by jermiy** [smc/Indic-Keyboard#30]
I could't run this in Android Studio at all.

**Comment by jishnu7** [comment]
It is possible. Make sure you did all the steps in HOWTO Build. You'll be able to import `java` folder in Android Studio, and use it.

**Comment by jermiy** [comment]
I did all but nothing. It complains that I don't have the manifest xml

**Comment by jermiy** [comment]
can you please help

**Comment by jermiy** [comment]
it keeps complaining this
Error:Android Source Generator: [Indic-Keyboard-master] AndroidManifest.xml file not found

**Comment by jermiy** [comment]
when i first wanted to make the project it complained that i don't have the output path, then i set it up to the folder location of the indic keyboard then i get the manifest problem.

**Comment by jishnu7** [comment]
Project has manifest file. look at java folder.
Are you sure you are importing java folder not the entire project?

**Comment by jermiy** [comment]
i did the entire folder and i fount the manifest from java folder and added to the path now i'm getting module error

**Comment by jishnu7** [comment]
no. you should import only java folder.

**Comment by siddik3436** [comment]
In gitshell when I command gradle assembleDebug. It show the following msg.......
A problem occurred configuring root project 'java'.
> Cannot evaluate module ime : Configuration with name 'default' not found.

**Comment by rafi-haque** [comment]
after, 'gradle assembleDebug' it says  "Cannot evaluate module ime : Configuration with name 'default' not found."
what should i do?

**Comment by westernwna** [comment]
I want to add custom language but when I import java folder, I got this problem.
anyway to solve it ?? thanks in advance.

Error:(50, 0) Cannot invoke method readLine() on null object.

**Comment by jishnu7** [comment]
you can delete those lines, those are there to read build key and other data from command line.

**Comment by westernwna** [comment]
Thanks for the time you give me to reply bro.

The gradle build procedure kinda working now.
And other new problems I get are....
Error:(49, 19) error: package org.smc.ime does not exist.
Error:(107, 13) error: cannot find symbol class InputMethod.
Error:(25, 40) error: package org.smc.inputmethod.indic.define does not exist.

I tried clean/rebuild project but no luck. Anyway to fix those errors??
Please help bro. Thanks you.

**Comment by asdofindia** [comment]
@westernwna did you do `git clone --recursive ...` as mentioned in [how-to](https://github.com/smc/Indic-Keyboard#howto-build)? If not, the submodules won't be downloaded. I guess you can fix this by doing [`git submodule update --init --recursive`](http://stackoverflow.com/a/6475033/589184)`

**Comment by jishnu7** [comment]
above comment should fix it.

**Comment by manjeets12** [comment]
@asdofindia  and jishnu7 I tried "git clone --recursive git@github.com:smc/Indic-Keyboard.git
" but it is producing authentication error mentioned below -
Cloning into 'Indic-Keyboard'...
Warning: Permanently added the RSA host key for IP address '192.30.252.131' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

is this project is not open source right now

**Comment by stultus** [comment]
@manjeets12  try using https instead of ssh while cloning.  or use a local fork of this repo
