### ISSUE TITLE
Pressing t (lower case) produces റ്റ rather than ട - ലിപ്യന്തരണം

### ISSUE THREAD

**Issue by syamcr** [smc/Indic-Keyboard#33]
t അമര്‍ത്തുമ്പോള്‍ ട ആണ് സ്വനലേഖയിലും മറ്റും വരുന്നത്. പക്ഷേ ഇവിടെ റ്റ ആണ് വരുന്നത്. ട വേണമെങ്കില്‍ T അമര്‍ത്തണം.

**Comment by balasankarc** [comment]
മൊഴി സ്കീമിനെ അനുസരിക്കണമല്ലോ.

**Comment by balasankarc** [comment]
Duplicate of #12

**Comment by jishnu7** [comment]
സ്വനലേഖ is implemented. will be available in next release.
