### ISSUE TITLE
Santali Ol Chiki support

### ISSUE THREAD

**Issue by aashiks** [smc/Indic-Keyboard#40]
From reddit : 

https://www.reddit.com/r/india/comments/37kpkl/np_indic_keyboard_v20_for_android_is_out_supports/crnzc72

Someone is querying if there are plans for Santali in Ol Chiki
##

**Comment by brawer** [comment]
In case it helps, XKeyboardConfig now has support for Ol Chiki:
http://cgit.freedesktop.org/xkeyboard-config/commit/?id=00bde378469aa374d646fd48a4a4d75229ebbc31

**Comment by jishnu7** [comment]
thanks @brawer. I'll have a look at it.

**Comment by jishnu7** [comment]
issue moved to gitlab: https://gitlab.com/smc/indic-keyboard/issues/44
