### ISSUE TITLE
Indic Keyboard -Version 2.0- English Keyboard Layout

### ISSUE THREAD

**Issue by ramesh-k** [smc/Indic-Keyboard#42]
ഇന്‍ഡിക്‍ കീബോര്‍ഡിന്റെ മുന്‍ വേര്‍ഷനിലെ ഇംഗ്ലീഷ് കീബോര്‍ഡില്‍ ഉണ്ടായിരുന്ന രൂപയുടെ ചിഹ്നം (₹) പുതിയ വേര്‍ഷനില്‍ (2.0) കാണുന്നില്ല.﻿ മുമ്പ് ഇംഗ്ലീഷ് കീബോര്‍ഡിലെ കീകള്‍ long press ചെയ്താല്‍ ഉപയോഗ പ്രദമായ ചിഹ്നങ്ങള്‍ ടൈപ്പ് ചെയ്യാമായിരുന്നു. എന്നാല്‍ ആ സംവിധാനം പുതിയ വേര്‍ഷനില്‍ കാണുന്നില്ല. പഴയ ഇംഗീഷ് കീ ബോര്‍ഡ് layout തന്നെയാണ് ഉപകാരപ്രദം. English (India) എന്ന പേരിലെങ്കിലും അത് ഉള്‍പെടുത്താമായിരുന്നു.

**Comment by jishnu7** [comment]
fixed. Will release a new version is a day or two.
