### ISSUE TITLE
Urudu transliteration issue

### ISSUE THREAD

**Issue by jishnu7** [smc/Indic-Keyboard#43]
Good app but I have one bug to report, Urdu transliteration is wrong (example: for s { س} it shows و which is "w". The same problem for all the letters) Otherwise a very good app.
- from reddit https://www.reddit.com/r/india/comments/37kpkl/np_indic_keyboard_v20_for_android_is_out_supports/crnlacw
##

**Comment by WaqasAliAbbasi** [comment]
I really want to use this beautiful app for Urdu typing. Any estimate when it would be fixed? Anyway I can help?

**Comment by jishnu7** [comment]
issue moved to gitlab: https://gitlab.com/smc/indic-keyboard/issues/47
