### ISSUE TITLE
keyboard unstable after 2.0.1 update

### ISSUE THREAD

**Issue by ffami** [smc/Indic-Keyboard#45]
I've found Indic keyboard v. 2.0.1 stopping often with the usual message "has stopped working". It resumes after few seconds. The settings enabled are default with only English and Malayalam keyboards enabled. If I can help with more logs or debug messages, please let me know. This is Android Kitkat on a moto X.

**Comment by jishnu7** [comment]
Yeah. It will be helpful if you share logcat log.

**Comment by jishnu7** [comment]
Can you give steps to reproduce?

I tried it in a device with android 4.4, not able to reproduce.

**Comment by ffayad** [comment]
Not able to confirm these are the exact steps but I saw that again by making changes in this order go to settings, enabling all malayalam keyboards, switching between system language and malayalam, typing some random words  and got the error. I am trying to get logcat log from a machine, this terminal emulator is confusing.

**Comment by jishnu7** [comment]
fixed the issue. will be releasing a version today.
