### ISSUE TITLE
App crashes after Step 2 during initial setup after installation in Cynagenmod 10.2.1 on Nexus 4

### ISSUE THREAD

**Issue by viggyprabhu** [smc/Indic-Keyboard#46]
I just installed the app from F-Droid and I am running Cynagenmod 10.2.1-mako version on LG Nexus 4 which is based on Android 4.3.1. After making the default keyboard as Indic-Keyboard in the initial setup, the app just crashed. I was also not able to use the keyboard anywhere as it was just crashing. I had to disable the keyboard and only then I could use the default English keyboard.
##

**Comment by jishnu7** [comment]
seems like F-Droid build has some issue. One more person reported this offline. For that person, play store build is working fine.

**Comment by jishnu7** [comment]
issue moved to gitlab: https://gitlab.com/smc/indic-keyboard/issues/49
