### ISSUE TITLE
Issue with ള്ള in Malayalam

### ISSUE THREAD

**Issue by sreejithk2000** [smc/Indic-Keyboard#47]
Issue #1
മൊബൈലിൽ 'ള്ള' എന്ന് ടൈപ്പ് ചെയ്യുക
എന്നിട്ട് രണ്ടാമത്തെ 'ള' മായ്ക്കുക. ആദ്യത്തെ 'ള' മായ്ക്കരുത്.
ഇനി 'ള' എന്ന് ടൈപ്പ് ചെയ്യാൻ ശ്രമിക്കുക.

'ല' എന്നേ വരൂ

Keyboard sequence: L L BackSpace BackSpace L

Issue #2
മൊബൈലിൽ 'ള്ള' എന്ന് ടൈപ്പ് ചെയ്യുക
എന്നിട്ട് രണ്ടാമത്തെ 'ള' മായ്ക്കുക. ആദ്യത്തെ 'ള' മായ്ക്കരുത്.
ഇനി 'ള' എന്ന് ടൈപ്പ് ചെയ്യാൻ ശ്രമിക്കുക.
'ല' എന്ന് ലഭിക്കും.
ഇനി 'ല' എന്ന് ടൈപ്പ് ചെയ്യുക.

Result: ളൢ⁠⁠⁠⁠

Keyboard squence: L L BackSpace BackSpace L l
##

**Comment by asdofindia** [comment]
Can confirm this in ലിപ്യന്തരണം keyboard. 
 
Though, for issue 1, L L backspace backspace backspace L a produces ള്ള

Is it important to fix such artificial sequences?

**Comment by gnuanu** [comment]
Not reproducible in Swanalekha.

On Mon, Jul 13, 2015 at 12:30 PM, Akshay S Dinesh <notifications@github.com>
wrote:

> Can confirm this in ലിപ്യന്തരണം keyboard.
>
> Though, for issue 1, L L backspace backspace backspace L a produces ള്ള
>
> Is it important to fix such artificial sequences?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smc/Indic-Keyboard/issues/47#issuecomment-120833224>.
>



-- 
അനൂപ് പനവളപ്പില്‍

**Comment by sreejithk2000** [comment]
The issue is with ലിപ്യന്തരണം keyboard. I confirm.

For the first issue, I do not think the sequence is artificial. I have encountered this multiple times. It is rare, but it is not unlikely. 

Issue 2 is artificial, I was playing around to see what other bugs does two capital 'L's can induce.

**Comment by sreejithk2000** [comment]
ഉദാഹരണത്തിന് എനിക്ക് 'ഉള്ളൂ' എന്ന് എഴുതണം എന്ന് വയ്ക്കുക. ഞാൻ ടൈപ്പ് ചെയ്തത് തെറ്റി 'ഉള്ളി' എന്നായിപ്പോയി. ഇത് തിരുത്താൻ ശ്രമിക്കുന്ന ഉപയോക്താവ് കുറച്ചൊന്ന് കഷ്ടപ്പെടും.

**Comment by stultus** [comment]
Confirmed issue 1 on ലിപ്യന്തരണം,  Not there in സ്വനലേഖ.  
Unable to Reproduce issue 2

**Comment by balasankarc** [comment]
Moved to GitLab: https://gitlab.com/smc/indic-keyboard/issues/50
