### ISSUE TITLE
Cannot build Java Directory in android studio.

### ISSUE THREAD

**Issue by westernwna** [smc/Indic-Keyboard#48]
When I tried to import java directory into android studio,
Gradle says,
Error:(50, 0) Cannot invoke method readLine() on null object

and line 50 is,
Line 50:  storeFile file(System.console().readLine("\n\$ Enter keystore path: "))

I tried removing signing configs and changed build type to Debug yet still not working.
It says "Error:Configuration with name 'default' not found."

Anyway to solve these problems??
I am from Burma and I want to modify some keys in Myanmar language to suite local user needs.
Thanks you.

**Comment by jishnu7** [comment]
you can modify the gradle file to fix this.

**Comment by anilkumark** [comment]
what type of modifications and where we need to do that modifications please let me know
