### ISSUE TITLE
ലിപ്യന്തരണം കീബോർഡുപയോഗിച്ച് ഉം എന്നടിച്ച് സ്പേസ് അമർത്തിയാൽ ഉസം എന്നു വരുന്നു

### ISSUE THREAD

**Issue by anoopnarayanan** [smc/Indic-Keyboard#52]
ഇൻഡിക് കീബോർഡിന്റെ മലയാളം ലിപ്യന്തരണം കീബോർഡുപയോഗിച്ച് ഉം എന്നടിച്ച് സ്പേസ് അടിച്ചാൽ ഉസം എന്നാകുന്നു.  ഓട്ടോ കരക്‌ഷൻ കോൺഫിഗറേഷൻ Modest ആയിട്ടും ഇത് വരുന്നുണ്ട്. ഉം എന്ന വാക്ക് പേർസണൽ ഡിക്ഷണറിയിലേക്ക് ആഡ് ചെയ്താൽ ഈ പ്രശ്നം ഒഴിവാകുന്നുണ്ട്. 

ഇഷ്യൂവിന്റെ സ്ക്രീൻ കാപ്ചർ വീഡിയോ ഇവിടെ കാണാം. 
https://twitter.com/anoopan/status/656330437929795584

app version: 2.0.2 
OS: android 5.1.1
##

**Comment by asdofindia** [comment]
പുനഃസൃഷ്ടിക്കാന്‍ കഴിഞ്ഞിട്ടുണ്ടു്. 
ലിപ്യന്തരണത്തില്‍ *ഉസം* എന്നും, ഇന്‍സ്ക്രിപ്റ്റില്‍ *നം* എന്നുമാണു് സജ്ജഷന്‍സ്. ഉം എന്നതു് ഒരു വാക്കല്ലാത്തോണ്ടാണെന്നു് തോന്നുന്നു.

**Comment by balasankarc** [comment]
Moved to GitLab: https://gitlab.com/smc/indic-keyboard/issues/45
