### ISSUE TITLE
മലയാളം ലിപ്യന്തരണം keyboard and Browsers issue with കൂട്ടക്ഷരം

### ISSUE THREAD

**Issue by vaikoovery** [smc/Indic-Keyboard#53]
മലയാളം ലിപ്യന്തരണം കീബോര്‍ഡ് ഉപയോഗിച്ച് ഗൂഗിളില്‍ കൂട്ടക്ഷരം വരുന്ന വാക്ക്/അക്ഷരം സെര്‍ച്ച് ചെയ്തതിനുശേഷം കൂട്ടക്ഷരം എഡിറ്റ് ചെയ്താല്‍ പിന്നീട് ആ കൂട്ടക്ഷരം മുറിയുന്നു.

ഉദാ:   "കൂട്ടാന്‍" എന്ന് സെര്‍ച്ച് ചെയ്തതിനുശേഷം ട്ട എഡിറ്റ് ചെയ്ത് വീണ്ടും അതേ വാക്കോ അല്ലെങ്കില് കൂട്ടക്ഷരം ഉള്‍പ്പെടുന്ന വേറെ വാക്കോ type ചെയ്താല്‍ ട്ട യ്ക്കു പകരം "ട" അല്ലെങ്കില്‍ ക്ക യ്ക്കു പകരം "ക" ക്ഷ യ്ക്കു പകരം "ഷ" ഒക്കെ ആയി മാറുന്നു.

വീണ്ടും സെര്‍ച്ച് ചെയ്യണമെങ്കില്‍ ടാബ് ക്ലോസ് ചെയ്ത് വീണ്ടും സെര്‍ച്ച് ചെയ്യേണ്ടി വരുന്നു.

Issues noted in Google Chrome (not in Google search app) & Xiaomi Browser. Issue couldn't replicate in Mozilla Firefox or Opera Mini.  
##

**Comment by asdofindia** [comment]
ഫയര്‍ഫോക്സില്‍ കൃത്യമായി പ്രവര്‍ത്തിക്കുന്നുണ്ടെന്നാണോ ഉദ്ദേശിച്ചതു്? മനസ്സിലാക്കിയിടത്തോളം എനിക്കു് കൃത്യമായി തന്നെ തിരുത്തിയെഴുതാന്‍ പറ്റുന്നുണ്ടു്. അതായതു് "കൂട്ടാന്‍" എന്നെഴുതിയതിനു് ശേഷം ട്ട മായിച്ചു് അവിടെ വീണ്ടും ട്ട തന്നെ എഴുതാന്‍ എനിക്കു് സാധിക്കുന്നുണ്ടു്. (Google Chrome, Xiaomi browser എന്നിവ ഇല്ലാത്തതിനാല്‍ മറ്റുള്ള ആപ്പുകളിലാണു് നോക്കിയതു്)

**Comment by vaikoovery** [comment]
അതെ. ഫയർഫോക്സിലും ഒപേര മിനിയിലും കൃത്യമായി പ്രവർത്തിക്കുന്നുണ്ട്.

ക്രോമിലാണ് ഈ പ്രശ്നം ആദ്യമായി കണ്ടത്. പിന്നീട് ടെസ്റ്റ് ചെയ്യുവാനായിട്ടാണ്
മറ്റ് ബ്രൗസറുകൾ നോക്കിയത്.

ഇപ്പോൾ ശ്രദ്ധിച്ചത്: ഗൂഗിൾ സെർച്ച് ടെക്സ്റ്റ് ബോക്സിൽ ഒരിക്കൽ എന്തെങ്കിലും
സെർച്ച് ചെയ്തതിനുശേഷം പുതിയൊരു കൂട്ടക്ഷരം വരുന്ന വാക്ക് ചേർത്താലും ഇതേ
പ്രശ്നം replicate ചെയ്യാൻ പറ്റുന്നുണ്ട്.

**Comment by balasankarc** [comment]
Moved to GitLab: https://gitlab.com/smc/indic-keyboard/issues/43
