### ISSUE TITLE
User reported bug: Bengali Dari is missing

### ISSUE THREAD

**Issue by jishnu7** [smc/Indic-Keyboard#54]
"Bengali full stop ("Dari" or "।" is missing from the keyboard, the dot full stop should be replaced by that. "

need to verify this first.

**Comment by jishnu7** [comment]
Another report -

U see this mark "।" (দাড়ি|Dari) should appear by pressing "." Bt it doesn't. This is very annoying. I hope u will fix it in next update.

**Comment by musfiqus** [comment]
Any update on this issue?

**Comment by SohanChy** [comment]
@jishnu7 I have fixed this annoying bug and submitted a pull request, 
Please review and merge.

**Comment by rajagopal067** [comment]
@jishnu7, hi What's the status of this bug. I want to work on this. Is this fixed ?

**Comment by jishnu7** [comment]
thanks for the interest @rajagopal067. Fix for this is in PR.

**Comment by jishnu7** [comment]
fixed.
