### ISSUE TITLE
User reported bug: Nukta in Odia

### ISSUE THREAD

**Issue by jishnu7** [smc/Indic-Keyboard#55]
Nukta in your odia keyboard is not working at all so that it is impossible to write yuktakshyaras with the message board of Samsung galaxy s 4 mini.

need to verify this.
##

**Comment by rajagopal067** [comment]
@jishnu7, Hi I want to work on this bug. What's the status of this bug, looks like has been open for a very long time.

**Comment by jishnu7** [comment]
not fixed yet.

**Comment by balasankarc** [comment]
Moved to GitLab: https://gitlab.com/smc/indic-keyboard/issues/41
