### ISSUE TITLE
How to build other dictionaries

### ISSUE THREAD

**Issue by Angtrim** [smc/Indic-Keyboard#56]
Hi,
I cloned you app and I would like to add other languages.
How can i build the CSV files and add them to the raw/ folder?
I tried using the .dict of the original LatinIME and modified the appropriate xml but it seems not to work.

**Comment by jishnu7** [comment]
You need to build `make-keyboard-text` binary, from tools/make-keyboard-text and then you can use the source file to build dict files.

**Comment by prathyush90** [comment]
Hi built a jar file from tools/make-keyboard-text and now how should i build .dict files??Is this the coreect process to build .dict files if not please suggest

**Comment by tearsofphoenix** [comment]
How to build `a jar file from tools/make-keyboard-text`, I'm an android newbee. @prathyush90
