### ISSUE TITLE
building from source

### ISSUE THREAD

**Issue by nilkashid** [smc/Indic-Keyboard#57]
Hi I tried to pull and build the project. It gives me following error :

`D:\indic-keyboard2>git clone --recursive https://github.com/smc/Indic-Keyboard.g
it
Cloning into 'Indic-Keyboard'...
remote: Counting objects: 9138, done.
remote: Total 9138 (delta 0), reused 0 (delta 0), pack-reused 9138
Receiving objects: 100% (9138/9138), 43.41 MiB | 82.00 KiB/s, done.
Resolving deltas: 100% (6025/6025), done.
Checking connectivity... done.
error: unable to create file graphic-assets/StoreListingIcon512*512.png (Invalid
 argument)
Checking out files: 100% (2183/2183), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'`

Is there anything missing. Need some help. As per logs says I tried to checkout with master. It works. But after opening with android studio it shows readLine() error I removed those signin configs and now it is showing following error:

`FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'java'.
> Cannot evaluate module ime : Configuration with name 'default' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED`

Need help. Thank you.

**Comment by jishnu7** [comment]
please have a look at other issues which are reported against building.
