### ISSUE TITLE
Authentication problem while cloning using git bash

### ISSUE THREAD

**Issue by manjeets12** [smc/Indic-Keyboard#60]
I used this command - "git clone --recursive git@github.com:smc/Indic-Keyboard.git" and got following errors -
"$ git clone --recursive git@github.com:smc/Indic-Keyboard.git
Cloning into 'Indic-Keyboard'...
The authenticity of host 'github.com (192.30.252.129)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.129' (RSA) to the list of know                                                      n hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
"
So it means either project is no more public or it isn't exit at that place, so can someone help me to find out what can be the real cause

**Comment by stultus** [comment]
Use https instead of ssh if you are cloning from the main repo. 
If you want to use ssh, make a fork and use that repository instead.

**Comment by manjeets12** [comment]
I had also cloned from  "git clone https://github.com/smc/Indic-Keyboard.git", and done successful build after removing gradle.build, but it was showing too many unused import errors when I tried to run it in emulator(or tried to generate apk), and hence I used method shown in How to build, 

I will see how to fork and check whether it will work or not

**Comment by asdofindia** [comment]
Please go through the [official github help](https://help.github.com/articles/error-permission-denied-publickey/) for this issue. The error you get has no relation to Indic-Keyboard

**Comment by manjeets12** [comment]
Solved- below are the problem and there solution I faced for successfully running this project in android studio
1)Authentication Error - follow [this](https://help.github.com/articles/error-permission-denied-publickey/) document to get public key for your computer(suggested by **asdofindia**);
after that you can successfully clone the project.
2)Too many unused imports after successful cloning(check if indic-keyboard/ime have something inside it or not, if it is empty follow step given below to run the project) - 

- after using this command "git clone --recursive git@github.com:smc/Indic-Keyboard.git" use cd indic-keyboard to navigate to project directory

- use "git submodule update --init --recursive" or "git submodule foreach --recursive git checkout master" as suggested by **asdofindia** and in [this](http://stackoverflow.com/questions/6474847/how-do-i-git-clone-recursive-and-checkout-master-on-all-submodules-in-a-single/6475033#6475033) stackoverflow question.

- then go to build.gradle in your clonned directory/indic-keyboard/java and remove signingConfigs and buildTypes part from it after saving import java folder to android studio and hopefully everything will work
