### ISSUE TITLE
Can this project be converted to a library?

### ISSUE THREAD

**Issue by manjeets12** [smc/Indic-Keyboard#61]
I am trying to convert this project into a library, by changing build.gradle, but I am getting few errors, so I just want to confirm can this project be convertible to library or not?If answer is not then I have to find other workaround, and if answer is yes then please check whether I am going in the right direction or not, I did below mentioned things to convert it to library -

-changed "apply plugin: 'com.android.application''  to "apply plugin: 'com.android.library", then synced the gradle and got this error - 

Error:Execution failed for task ':java:transformNative_libsWithSyncJniLibsForRelease'.

> java.io.FileNotFoundException: C:\Users\user\Indic-Keyboard\java\build\intermediates\bundles\release\jni\lib\armeabi-v7a\libjni_latinime.so (The system cannot find the path specified)
> -to resolve it I added armeabi.jar to lib in that path but still getting same error( as on build project structure changing back to its original state) , and this is the place where I stuck from a long while,
##

**Comment by jishnu7** [comment]
converting into a library is not simple as changing a variable in build.gradle, especially since this is an input method, which relies on system settings.

**Comment by manjeets12** [comment]
Thanks for the response,that will help me to focus other workaround

**Comment by manjeets12** [comment]
Hi jishnu7, can you please provide some guidance or documentation to read for converting an input method into a library.

as far as I guess, I may need to create .iml file or find something to stop default build functionality,

**Comment by asdofindia** [comment]
[This sitepoint tutorial](http://www.sitepoint.com/getting-started-with-android-library-projects-part-1/) looks like a good introduction if you want to understand how to build a library.

**Comment by manjeets12** [comment]
thanks asdofindia, I tried tutorial suggested by you and I am somewhat successful, but now I want to know how can I use small parts of this project(with credits given where due) within my library, because as I am trying to remove xmls not required for my project i got 1000 of errors, what i tried is created a new res_kbd folder and copied the required xmls for hindi there(by given proper references) but I am getting lots of errors, so can you please help me to code in backward direction

**Comment by asdofindia** [comment]
No I can't. Sorry.
