### ISSUE TITLE
Empty items in the checklist.

### ISSUE THREAD

**Issue by arushidogra** [smc/Indic-Keyboard#62]
While choosing the language , In the check list there were some empty fields . 
@jishnu7 , can you please see this? 
![indic_checklist](https://cloud.githubusercontent.com/assets/9354396/13899458/90a6a624-ee14-11e5-888e-3b0f2f6ca8f0.jpg)

**Comment by asdofindia** [comment]
Seems more like this phone doesn't have the font to display what's written there. What version of Android, which model of phone?

**Comment by arushidogra** [comment]
Android version : 4.4.4
Model : MotoE

**Comment by jishnu7** [comment]
This is because of the lack of fonts in the system. We can't do anything from our side, the manufacturer has to support it.
