### ISSUE TITLE
Indic Keyboard sometimes hangs on Samsung Galaxy S6 Edge

### ISSUE THREAD

**Issue by dhanush** [smc/Indic-Keyboard#63]
I had no problems in using Indic keyboard in my earlier phone, but in my current phone the keyboard hangs sometimes and is stuck always on the screen. I have to restart the phone to use the keyboard again. This happens mostly when I type English.

**Comment by jishnu7** [comment]
Can give more details. Like when it happens, is it happening for all apps, OS version etc.

Also, it will be more helpful if you can take screenshots / some photos or even better a video recording.

**Comment by dhanush** [comment]
I am using Android version 5.1.1. I have noticed it happening more when I use twitter. I will attach a screenshot next time when it happens
