### ISSUE TITLE
Add swipe text in english

### ISSUE THREAD

**Issue by gauthamzz** [smc/Indic-Keyboard#66]
Its easier to type using swipe text in google keyboard.Since i use indic keyboard for malayalam i dont want to change keyboard everytime.It would be good if there was swipe text for englsih

**Comment by jishnu7** [comment]
Please download https://play.google.com/store/apps/details?id=in.androidtweak.inputmethod.indic for swipe input.

**Comment by gauthamzz** [comment]
But it doesn't work properly തെങ്ങ becomes വ്വെര്മ . so I thought an official one would be better
