### ISSUE TITLE
Odia Keyboard - user reported bug

### ISSUE THREAD

**Issue by jishnu7** [smc/Indic-Keyboard#67]
`This key board is not working properly. While writing yutkakshyara halant seems to be dead. For example while writing -pakwa- pa+k+halant+ba it is shown as pakba(wrong). Please correct the keyboard with reference to Akruti odia Fonts as soon as possible.
For your information my hand set is Samsung Galaxy s-4 mini gt-19192.`

`Yuktakshyar in odia keyboard is not working in due manner. Please, correct the error. My handset is Samsung galaxy mini xl gt-19192.`
##

**Comment by balasankarc** [comment]
Moved to GitLab: https://gitlab.com/smc/indic-keyboard/issues/39
