### ISSUE TITLE
~ സിംബൽ മെയിൻ സിംബൽ കീബോർഡിലേക്ക് മാറ്റിയാൽ നന്നായിരിക്കും

### ISSUE THREAD

**Issue by ptsubin** [smc/Indic-Keyboard#7]
് ചിഹ്നം ചേർക്കാനുപയോഗിക്കുന്ന ~ സിംബൽ ഇപ്പോൾ മെയിൻ സിംബൽ കീബോർഡിൽ ഇല്ല. ഇത് ടൈപ്പിങ്ങ് കൂടുതൽ എളുപ്പത്തിലാക്കാൻ സഹായിക്കും എന്ന് തോന്നുന്നു.

**Comment by jishnu7** [comment]
added. will be there in next release.
