### ISSUE TITLE
Changing language from another app?

### ISSUE THREAD

**Issue by mathiazhagan01** [smc/Indic-Keyboard#77]
Is there any option to dynamically change language from another app? i.e., Keyboard language should change according to the locale.
##

**Comment by jishnu7** [comment]
You should check https://github.com/libindic/libindic-sdk.

**Comment by mathiazhagan01** [comment]
@jishnu7 There is no sample codes, example or instruction. Can you please explain about that sdk?

**Comment by jishnu7** [comment]
check the demo app https://github.com/libindic/sdk-demo
