### ISSUE TITLE
change keyboard language as per app locale

### ISSUE THREAD

**Issue by srinivas3120** [smc/Indic-Keyboard#78]
can we change keyboard language and should be changed to the locale of android application(app level). how can i achieve this?
##

**Comment by jishnu7** [comment]
Not sure how to do it. Keyboard supports system level locale.

**Comment by jishnu7** [comment]
You should check https://github.com/libindic/libindic-sdk. Which is give better control and you can pack it along with your app

**Comment by srinivas3120** [comment]
can we get all supported keyboard languages on the android device.
how do i get languages that were supported on google keyboard or swiftkey keyboard.

i am able to get supported keyboards like google keyboard, swiftkey keyboard (if installed on device). 
`InputMethodManager imm = (InputMethodManager) getSystemService(Context.INPUT_METHOD_SERVICE);
    List<InputMethodInfo> mInputMethodProperties = imm.getEnabledInputMethodList();

    final int N = mInputMethodProperties.size();

    for (int i = 0; i < N; i++) {
      InputMethodInfo imi = mInputMethodProperties.get(i);
      String imi.getId(); // id of the input method
}`

**Comment by balasankarc** [comment]
Moved to GitLab: https://gitlab.com/smc/indic-keyboard/issues/37
