### ISSUE TITLE
Native code compilation

### ISSUE THREAD

**Issue by Separius** [smc/Indic-Keyboard#79]
Hi,
I have successfully compiled the keyboard using gradle, but when I try to build the native part myself, the compiled shared object does not work (I use it by changing java/libs/armeabi.jar) and I get:

```
E/BinaryDictionaryFileDumper: No permission to communicate with the dictionary provider
java.lang.SecurityException: Permission Denial: opening provider com.android.inputmethod.dictionarypack.DictionaryProvider from ProcessRecord{f450e2f 20225:in.android.inputmethod.indic/u0a280} (pid=20225, uid=10280) that is not exported from uid 10111
```

Any ideas? (obviously I have READ_USER_DICTIONARY permission and I have also exported DictionaryProvider in the manifest)

Edit1(irrelevant): the working (provided) shared object is 677.5 kB, but mine is 931.4 kB
Edit2: [same question](http://stackoverflow.com/questions/38938808/permission-denial-opening-provider-com-android-inputmethod-dictionarypack-dicti)
##

**Comment by Separius** [comment]
My bad, ch.ethz.disco.lpeer.inputmethodtwo.latin was interfering and caused Permission Denial, but deleting the other keyboard does not solve the problem, I still don't have gesture input via my own native build (precompiled one has gesture input)
And I also get these(both via my own build and the precompiled version):
```
E/ActivityThread: Failed to find provider info for com.android.inputmethod.dictionarypack.aosp
E/BinaryDictionaryFileDumper: Can't establish communication with dictionary provider
```

**Comment by balasankarc** [comment]
Moved to GitLab: https://gitlab.com/smc/indic-keyboard/issues/35
