### ISSUE TITLE
Add support for emojis

### ISSUE THREAD

**Issue by FleetAdmiral** [smc/Indic-Keyboard#80]
I've been using the keyboard for a few days and have found the lack of emoji inputs frustrating. To make the keyboard more functional and useful, i feel an emoji input option must also be added that allows user to type in emojis as well (most 3rd party keyboards like swift already have this option).

I'd like to work on it if it is to be implemented.

**Comment by FleetAdmiral** [comment]
Any updates on this?

**Comment by balasankarc** [comment]
@FleetAdmiral Long press on Enter key can give you Emojis


![tmp_20689-screenshot_20161218-082917-1301313633](https://cloud.githubusercontent.com/assets/2379271/21291185/326a03ca-c4fc-11e6-9367-b8900b2b8c29.png)


![tmp_20689-screenshot_20161218-0829221115905828](https://cloud.githubusercontent.com/assets/2379271/21291189/4351cb14-c4fc-11e6-981e-41449531be17.png)

**Comment by jishnu7** [comment]
@FleetAdmiral Thanks for reporting the bug. 
Like @balasankarc posted above. Emojis are already supported. But we know that it is not in a prominent, easy to find place.
Next version of the keyboard, which I'm working on right now, will have better support.

**Comment by FleetAdmiral** [comment]
Alright, hadn't seen it in the tutorial so maybe if you could have a guided tutorial and mention this there it'd be nice. @jishnu7 Is the project being shifted to another repository because i'm using the keyboard as my default keyboard and would like to report and work on/contribute enhancements or issues i find, if thats fine with you?

**Comment by jishnu7** [comment]
Yeah we are lacking good contributions in tutorials. May be you can write one?

Project is not moving. I'm just upgrading the code to the latest aosp base.

We always welcome contributions.

**Comment by FleetAdmiral** [comment]
@jishnu7 Yea, i'll start work on the guided tutorial! 

Also, would you be applying for GSoC this year?

**Comment by jishnu7** [comment]
If you are talking about tutorial inside the app, then I won't recommend doing it right away. A lot of code related to that is changing, and there are already some changes pending in PRs. It might become a a double work. I recommend you to star with something else. If you really want to do tutorial, then I suggest you to write blog posts (which we can publish in indiproject / smc website), video tutorials or even create a website itself for Indic Keyboard.

About GSoC, We might apply again for next year.

**Comment by FleetAdmiral** [comment]
@jishnu7  Alright, i'll hold off on any android issues until further notice. I could write a blog post but i feel that there would be more of a use if we make a website for Indic keyboard by itself, so i'll work on that.
Any requirements as of now? 
Also, where should i push it to? I feel it'd be better if we had a public repo under your organisation so that others can contribute to that if they wish to.

**Comment by FleetAdmiral** [comment]
@jishnu7 ^Could you let me know where i can maintain the website if i work on it? Is there already a repository i could work in, maybe if you intend this to be a subdomain or static page of an already existing website?

**Comment by jishnu7** [comment]
@FleetAdmiral Here is the repo.
https://gitlab.com/smc/indic-keyboard-website
There were few people working on it before, I asked them to upload the files. Not sure how much progress they made in HTML/CSS. There is a design source file available. They will upload that for sure.

**Comment by FleetAdmiral** [comment]
@jishnu7 The repo is empty as of now, should i ask for the files to be uploaded on irc?

**Comment by jishnu7** [comment]
@FleetAdmiral I'll ping the person responsible for uploading the files, again.

**Comment by jishnu7** [comment]
Hey @FleetAdmiral got the files -> https://gitlab.com/rejah/Indic-Keyboard-Webpage/

**Comment by FleetAdmiral** [comment]
Got the design files! I'll start working on it and keep you updated.

**Comment by jishnu7** [comment]
thanks @FleetAdmiral . you can send PRs to https://gitlab.com/smc/indic-keyboard-website. I'll make sure they get merged.

**Comment by jishnu7** [comment]
or, just give me your gitlab account, I'll add you for the repo, so that you can directly push your code.

**Comment by FleetAdmiral** [comment]
That'll do! My gitlab username is FleetAdmiral (https://gitlab.com/FleetAdmiral).
Also, i'm guessing this will be a single page application (in accordance with the psd design files), something like http://demo.massivedynamic.co/app1/? 
Right?
