### ISSUE TITLE
മലയാളം ലിപ്യന്തരണം കീബോർഡിൽ വാക്കുകൾ എഡിറ്റ് ചെയ്യാൻ സാധിക്കുന്നില്ല.

### ISSUE THREAD

**Issue by anoopnarayanan** [smc/Indic-Keyboard#9]
മലയാളം ലിപ്യന്തരണം കീബോർഡിൽ വാക്കുകൾ എഡിറ്റ് ചെയ്യാൻ സാധിക്കുന്നില്ല. വാക്കുകൾ എഡിറ്റ് ചെയ്യാൻ ശ്രമിക്കുമ്പോൾ മലയാളത്തിനു പകരം ഇംഗ്ലീഷ് ആണു വരുന്നത്. ഉദാഹരണത്തിനു 'വിക്കിപ്പീഡിയ' എന്നെഴുതി ആ വാക്ക് വിക്കിപീഡിയ എന്നാക്കാൻ ശ്രമിക്കുമ്പോൾ വിക്കിpiഡിയ എന്നു വരുന്നു. ഇപ്പോൾ വാക്കു പൂർണ്ണമായും ഡിലീറ്റ് ചെയ്ത് വീണ്ടും എഴുതുകയാണു ചെയ്യുന്നത്.

**Comment by jishnu7** [comment]
fixed.

**Comment by tachyons** [comment]
:+1:
